language: ruby

services:
  - docker

before_install:
  - docker pull amazoncorretto:11
  - docker create volume artifact_volume
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker run --name project-builder -v $PWD:/source amazoncorretto:11 /bin/sh -c "cd /source ; ./gradlew clean build docker dockerPush"

