language: ruby

services:
  - docker

before_install:
  - docker pull amazoncorretto:11
  - docker pull google/cloud-sdk:249.0.0-alpine
  - openssl aes-256-cbc -K $encrypted_5f81bad43974_key -iv $encrypted_5f81bad43974_iv -in helpful-range-236813-681ca732dc15.json.enc -out helpful-range-236813-681ca732dc15.json -d


script:
  - docker run --rm -v $TRAVIS_BUILD_DIR:/source -v artifact_volume:/artifact_volume amazoncorretto:11 /bin/sh -c "cd /source ; ./gradlew clean build"
  - docker build -t joelin/nextpos-service:latest --build-arg JAR_FILE=build/libs/nextpos-service-0.0.1-SNAPSHOT.jar .
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push joelin/nextpos-service:latest


after_script:
  - docker run --rm -v $TRAVIS_BUILD_DIR:/source google/cloud-sdk:249.0.0-alpine /bin/sh -c "cd /source ; sh deploy_gcp.sh"
  