language: ruby

services:
  - docker

before_install:
  - docker pull amazoncorretto:11
  - docker volume create artifact_volume
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker run --rm -v $TRAVIS_BUILD_DIR:/source -v artifact_volume:/artifact_volume amazoncorretto:11 /bin/sh -c "cd /source ; ./gradlew clean build docker dockerPush"
  #- docker build -t nextpos-service --build-arg JAR_FILE="$TRAVIS_BUILD_DIR/build/libs/nextpos-service-0.0.1-SNAPSHOT.jar" .


