apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextpos-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextpos-service
  template:
    metadata:
      labels:
        app: nextpos-service
    spec:
      containers:
      - name: nextpos-service
        image: docker.io/joelin/nextpos-service:latest
        ports:
          - containerPort: 8080
        env:
          - name: PROFILE
            value: gcp
        volumeMounts:
          - mountPath: /config
            name: application-props
            readOnly: true
      volumes:
        - name: application-props
          configMap:
            name: application-gcp-props
            defaultMode: 420
            items:
              - key: application-gcp.properties
                path: application-gcp.properties
