apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextpos-ingress
spec:
  tls:
    - secretName: nextpos-secret-tls2
  defaultBackend:
    service:
      name: nextpos-service-nodeport
      port:
        number: 80
