# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
workflows:
  test-env-vars:
    jobs:
      - build:
          context:
            - "GitHub Release Credentials"
            - "Docker"
jobs:
  build:
    docker:
      - image: amazoncorretto:11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew clean build -x test -PciBuild
  deploy:
    docker:
      - image: google/cloud-sdk:249.0.0-alpine
    steps:
      - run: |
        echo $GOOGLE_SERVICE_ACCOUNT_JSON | base64 --decode | docker build -t joelin/nextpos-service:latest --build-arg JAR_FILE=build/libs/nextpos-service-0.0.1-SNAPSHOT.jar --build-arg SERVICE_ACCOUNT_JSON=- .
      - run: |
        echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: |
        docker push joelin/nextpos-service:latest
